### ISSUE TITLE
Plugin: Install and configure ADR viewer plugin

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#14]
Install and configure ADR viewer

https://github.com/backstage/backstage/tree/master/plugins/adr

**Comment by SamoKopecky** [comment]
The same is happening here as with #18, the plugin requires GitHub OAuth app to work properly.

**Comment by SamoKopecky** [comment]
I've since asked on the backstage discord server if there exists any other way to make this work, they told me this only works with GitHub OAuth.

Should we just create a link for this in the `Links` section in the service overview for now? We can then find a better solution after the demo.
The link will be here:
![image](https://user-images.githubusercontent.com/44006847/178260834-142cfc67-3f2d-41aa-984a-189c7755e1a1.png)
