### ISSUE TITLE
Service catalog instance is failing liveliness probe

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#171]
### Describe the problem

For some reason the instance is being killed:

https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/service-catalog/pods/service-catalog-558dbcf8b5-6s8wh

![image](https://user-images.githubusercontent.com/7453394/199741421-bb4403ac-2274-45e2-bd5e-a6669b296348.png)

### Steps to reproduce the problem

1. https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/service-catalog/pods/service-catalog-558dbcf8b5-6s8wh
2. See events

Or:

1. Go to https://service-catalog.operate-first.cloud/
2. Sometimes you get app not available because the pod is restarting

**Comment by SamoKopecky** [comment]
The pod restarts when this happens:
```
Liveness probe failed: Get "http://10.130.9.96:7007/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

I found a related issue thread [here](https://github.com/kubernetes/kubernetes/issues/89898), it looks like the problem is with the `httpGet` probe and switching to `exec` probe seemed to fix the problem, I suggest we try switching to the `exec` probe to see if the problem still persists.

**Comment by SamoKopecky** [comment]
I'll watch the deployment a bit longer, if no errors pop up, I will close this issue.

**Comment by SamoKopecky** [comment]
10+ hours without any restarts, seems to fixed.
/close
