### ISSUE TITLE
Plugin: Install and configure Github insights plugin

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#18]
Display more information about github repos in Backstage.

https://roadie.io/backstage/plugins/github-insights/?utm_source=backstage.io&utm_medium=marketplace&utm_campaign=github-insights

**Comment by SamoKopecky** [comment]
GitHub Insights plugin requires [GitHub OAuth](https://backstage.io/docs/auth/oauth#sequence-diagram), which would require users to login with GitHub to view insights. I've tried to utilize the [GitHub integrations](https://backstage.io/docs/integrations/github/github-apps), using GitHub Apps and a personal access token, but none worked because the plugin uses only OAuth authentication.
