### ISSUE TITLE
Feature: Add a flag for featured services

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#51]
Home screen with service/component tiles can get cluttered pretty fast. Add support for a toggle/flag annotation `operate-first.cloud/featured: "true"` that will be used as a filter. Only services which have this flag should be displayed.

Try using [`GetEntitiesRequest.filter`](https://backstage.io/docs/reference/catalog-client.getentitiesrequest.filter) on 

https://github.com/operate-first/service-catalog/blob/ec4667485a65e4375e06c480a12d86c25f455622/packages/app/src/components/home/HomePage.tsx#L83

Acceptance criteria:
- [x] Implement this functionality to backstage (#79)
- [x] Add these feature flags to some of the `Components` in our service-catalog (https://github.com/operate-first/apps/pull/2205)

**Comment by SamoKopecky** [comment]
/close

Can be verified by viewing the [service catalog](service-catalog.operate-first.cloud/) and checking the config files for the catalog ([this](https://github.com/operate-first/apps/blob/master/service-catalog/components/crunchy-postgres-db.yaml) entity is not shown because it doesn't have the annotation).
