### ISSUE TITLE
Configure Kubernetes plugin to access all Operate First clusters

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#59]
Follow up to https://github.com/operate-first/service-catalog/issues/12

Make Backstage aggregate connections to multiple clusters.

- [x] Refactor https://github.com/operate-first/apps/pull/2156 so it included in all clusters, always, with appropriate service account.
- [x] Investigate if we can use Vault to pass tokens from individual clusters to single secret in service catalog namespace.
- [x] Aggregate all cluster configs into Backstage, at first pass we inline it into the config verbatim.
- [x] Create documentation (#104)

**Comment by SamoKopecky** [comment]
I've done some research and I've come up with a possible solutions:

1. Assuming we have all the required `ServiceAccounts`/`ClusterRoles`/`ClusterRoleBindings` deployed on all the clusters, we can use the [Kubernetes secrets engine](https://developer.hashicorp.com/vault/docs/secrets/kubernetes#kubernetes-secrets-engine) which will allow us to save ServiceAccount Tokens to the vault via the [vault CLI](https://developer.hashicorp.com/vault/docs/commands) (see [generating credentials](https://developer.hashicorp.com/vault/docs/secrets/kubernetes#generating-credentials)).

2. I don't think there is a declarative way to generate the service account tokens, so maybe we could use a `CronJob` that runs a script each time the token is about to expire. We can set this up using the [TTL parameter](https://developer.hashicorp.com/vault/docs/secrets/kubernetes#ttl), that means we can set the TTL to an hour and run the `CronJob` everyone 30 minutes, or something similar with longer time periods like days or months.

3. Once we have generated tokens for ServiceAccounts we can use an `ExternalSecret` to query all the tokens into a single secret in the `service-catalog` namespace. We can query all the tokens at once using [multiple secrets query](https://external-secrets.io/v0.5.6/provider-hashicorp-vault/#getting-multiple-secrets).

Another solution is this:
1. Again we assume we have all the required `ServiceAccounts`/`ClusterRoles`/`ClusterRoleBindings` deployed on all the clusters.  We can then either run a `tekton task` or a `CronJob` on a fixed schedule (although I wasn't able to find a way to a tekton task on a cron schedule in the documentation) to fetch all the auto generated SA tokens into our vault instance. 

2. The fetching process would consist of creating a bash script that would read the secret that contains the SA token and it would push the token to our vault instance via the [vault CLI](https://developer.hashicorp.com/vault/docs/commands). The `CronJob` would use the `oc` binary to query the secret so that no tokens for authenticating to the cluster are required.

3. Then we can do the same thing as the first solution where we create an `ExternalSecret`.

In booth scenarios the `CronJobs` would be running on the same cluster that they are creating/fetching the SA token for.

WDYT @tumido?
